# Generated by Django 4.2 on 2026-04-22 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_city_state_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_attachment',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_attachment',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_attachment',
            field=models.FileField(blank=True, null=True, upload_to='pan_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_type', models.CharField(choices=[('open', 'Open Body'), ('closed', 'Closed Body'), ('container', 'Container'), ('freezer', 'Freezer/Reefer'), ('tipper', 'Tipper/Dumper'), ('tanker', 'Tanker')], default='open', max_length=20)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric')], default='diesel', max_length=20)),
                ('max_weight_capacity', models.DecimalField(decimal_places=2, default=0, help_text='Maximum weight in KG', max_digits=10)),
                ('max_volume_capacity', models.DecimalField(decimal_places=2, default=0, help_text='Maximum volume in cubic feet', max_digits=10)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('rc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rc_attachment', models.FileField(blank=True, null=True, upload_to='rc_documents/')),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('insurance_attachment', models.FileField(blank=True, null=True, upload_to='insurance_docs/')),
                ('fitness_validity', models.DateField(blank=True, null=True)),
                ('permit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('permit_attachment', models.FileField(blank=True, null=True, upload_to='permits/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('on_trip', 'On Trip')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trucks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
    ]
