# Generated by Django 4.2 on 2026-04-23 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_user_aadhar_attachment_user_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name (e.g., Cement, Rice, Medicine Box)', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Item code/SKU', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('size', models.CharField(blank=True, help_text='Size (e.g., 50kg, 1x2ft, 10x10)', max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'KG (Kilogram)'), ('g', 'G (Gram)'), ('qtl', 'QTL (Quintal)'), ('ton', 'TON (Ton)'), ('pcs', 'Pieces'), ('box', 'Box'), ('bag', 'Bag'), ('bundle', 'Bundle'), ('roll', 'Roll'), ('meter', 'Meter'), ('feet', 'Feet'), ('liter', 'Liter')], default='kg', max_length=20)),
                ('weight_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Weight per unit in KG', max_digits=10)),
                ('default_freight_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default freight rate per KG/QTL', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
    ]
