# Generated by Django 4.2 on 2026-04-23 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_party_id_alter_truck_id_alter_user_id_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builty_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=15)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_hamali', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_billi_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='pending', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_person', models.CharField(blank=True, max_length=100)),
                ('pod_attachment', models.FileField(blank=True, null=True, upload_to='pod_documents/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_builty', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_builty', to='transport.party')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_builty', to='transport.party')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.truck')),
            ],
            options={
                'verbose_name': 'Builty',
                'verbose_name_plural': 'Builty',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BuiltyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hamali', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billi_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('builty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transport.builty')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.item')),
            ],
        ),
    ]
